name: "Setup AWS Copilot CLI"

inputs:
  version:
    description: "Copilot CLI version"
    required: false
    default: "latest"

runs:
  using: "composite"

  steps:
    - name: Install Copilot CLI
      shell: bash
      run: |
        curl -Lo /usr/local/bin/copilot "https://github.com/aws/copilot-cli/releases/download/${{ inputs.version }}/copilot-linux"
        chmod +x /usr/local/bin/copilot
